# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: askhan1497
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
